### ISSUE TITLE
Create a Web page

### ISSUE THREAD

**Issue by Ieslen** [tonbotelho/YearsSinceLearningtoCode#1]
We need create a web application to show the data from the CSV file

**Comment by Ieslen** [comment]
Guys,

Can you look at this: https://developers.google.com/chart/interactive/docs/quick_start

Just an idea for our webpage .. this is in javascript

**Comment by Ieslen** [comment]
Guys,

Can you look at this: https://developers.google.com/chart/interactive/docs/quick_start

This is an idea for our chart .. html + javascript

**Comment by LianeSheehy** [comment]
Great, we can display an example, base on this codes. thanks, Ieslen
