### ISSUE TITLE
Calculate data required for presentation 

### ISSUE THREAD

**Issue by tonbotelho** [tonbotelho/YearsSinceLearningtoCode#10]

**Comment by Ieslen** [comment]
5 points

**Comment by Ieslen** [comment]
Created a calculation math because "order by" by pandas was not working.  Used a sum by years to order the values.
Implemented it for both columns
name1 = (sum(list(map(int, i))), r[10])
name1 = (sum(list(map(int, i))), r[11])
e.g:
             # 0-2 = 2
            # 3-5 = 8
            # 6-8 = 14
            # 9-11 = 20
            # .
            # .
            # 18-20 = 38
            # 24-26 = 50
            # 30 > more
