### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Ieslen** [tonbotelho/YearsSinceLearningtoCode#15]
Test the percentage

**Comment by yuliakurt** [comment]
[test survey data.xlsx](https://github.com/tonbotelho/YearsSinceLearningtoCode/files/2571667/test.survey.data.xlsx)

Guys, "All respondents" is fine, but in "Professional developers" the numbers differ significantly.

**Comment by Ieslen** [comment]
Hi Julia,

your calculation for Professional Developers is based on 87259  respondents, however the sum of your excel for this group is 77903, so, the percentage will be different.

Professional Developers:  

respondents | Project data | Website data
23421 | 30.1 | 9.6
21362 | 27.1 | 24.4
11385 | 14.1 | 21.4
7573 | 9.1 | 13.5
4287 | 5.1 | 8.9
3012 | 3.1 | 6.8
2830 | 3.1 | 5.6
1368 | 1.1 | 2.9
857 | 1.1 | 2.0
506 | 0.1 | 1.2
1302 | 1.1 | 3.8

sum first column = 77903 

87259   respondents

**Comment by yuliakurt** [comment]
Hi Lely,

I took the number of the respondents from the website. If we count with 77903, my numbers differ from yours. I counted with the formula = N respondent * 100 / total respondents number. Below are results with 77 903. 
The same formula was used for All Respondents and I don't understand why the difference is so big. What formula did you use?




Professional Developers: |   |  
  |   |  
respondents | Project data | Website data
23421 | 29.1 | 9.6
21362 | 26.1 | 24.4
11385 | 13.1 | 21.4
7573 | 8.1 | 13.5
4287 | 4.1 | 8.9
3012 | 2.1 | 6.8
2830 | 2.1 | 5.6
1368 | 31.12 | 2.9
857 | 31.12 | 2.0
506 | 30.12 | 1.2
1302 | 31.12 | 3.8
  |   |  
87259 respondents / 77903
