### ISSUE TITLE
Have chart reading from a csv file

### ISSUE THREAD

**Issue by tonbotelho** [tonbotelho/YearsSinceLearningtoCode#3]

**Comment by LianeSheehy** [comment]
Hey, guys, I have been searching how to read CSV file with python, I have the code but for some reason when I run the programme it can't find my file. 
there is two way to do it:
number 1:
import CSV
path = 'C:\Users\Liane Silva\Desktop\3 semester\Group Project\survey_results_public.csv'
file = open(path)
for line in file:
    print(line)
--------------------------------------------------------------------------------------------------------
number 2:
import CSV
with open ('survey_results_public.csv', 'r') as file:
    csv_reader = csv.reader(file)
    for line in csv_reader:
        print (line)

**Comment by Ieslen** [comment]
Hi Liane,

I  have a java code done from my OOD2 class, where I create and read a csv file. So we can try just switch from java to python language. We can try to do it together after Project2 class.

**Comment by LianeSheehy** [comment]
Perfect, 

I see you tomorrow then. 

thanks Ieslen
