### ISSUE TITLE
 Display a python chart in a webpage

### ISSUE THREAD

**Issue by tonbotelho** [tonbotelho/YearsSinceLearningtoCode#4]

**Comment by Ieslen** [comment]
Liane,

Look this: https://developers.google.com/chart/interactive/docs/quick_start

**Comment by Ieslen** [comment]
Hi Ton,

Follow here some sites that we can use to output the data on the screen:
https://www.w3schools.com/jquery/ajax_getjson.asp
https://docs.python-guide.org/scenarios/json/
https://docs.python-guide.org/scenarios/json/
https://www.hostingadvice.com/how-to/javascript-add-to-array/
https://jsfiddle.net/api/post/library/pure/
